version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      —character-set-server=utf8mb4
      —collation-server=utf8mb4_general_ci

volumes:
  mysql-data: